- name: Install dependency packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - wireguard

- name: Enable service wireguard
  become: true
  systemd:
    name: wireguard
    enabled: yes
    masked: no
    state: restarted
