export default {
    'form.flashes.success': 'Success',
    'form.helps.nick-name': 'Nick name is your unique ID to sign in, between 2 to 32 charaters.',
    'form.helps.password': 'Password must at least 6 characters.',
    'form.labels.body': 'Body',
    'form.labels.content': 'Content',
    'form.labels.email': 'Email',
    'form.labels.nick-name': 'Nick name',
    'form.labels.password': 'Password',
    'form.labels.password-confirmation': 'Password confirmation',
    'form.labels.real-name': 'Real name',
    'form.labels.username': 'User name',
    'form.validations.email': 'Bad email address.',
    'form.validations.nick-name': "Nick name must between 2~32 characters and without special characters.",
    'form.validations.password': 'Password must at least has 6 characters.',
    'form.validations.password-confirmation': 'Passwords not match.',
    'form.validations.username': "Username must between 2~32 characters.",
}