export default {
    'home.title': 'Home',
    'install.success': 'Init database successed, you can sign in to continue now.',
    'install.title': 'Init database',
    'leave-words.new.help': 'Please leave your contact information for us to replay to you.',
    'leave-words.new.title': 'Leave a message',
    'users.change-password.success': 'Your password has been changed successfully.',
    'users.change-password.title': 'Change your password',
    'users.confirm.success': 'You will receive an email with instructions for how to confirm your email address in a few minutes.',
    'users.confirm.title': "Didn't receive unlock instructions?",
    'users.forgot-password.success': 'You will receive an email with instructions on how to reset your password in a few minutes.',
    'users.forgot-password.title': 'Forgot your password?',
    'users.reset-password.title': 'Reset your password',
    'users.sign-in.login': 'Nick name/Email',
    'users.sign-in.title': 'Sign in',
    'users.sign-up.title': 'Sign Up',
    "users.unlock.success": 'You will receive an email with instructions for how to unlock your account in a few minutes.',
    'users.unlock.title': "Didn't receive confirmation instructions?",
}