- name: Update repositories cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist

- name: Install dependency packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - software-properties-common
      - apt-transport-https
      - python3-pip
      - systemd-cron
      - pwgen
      - tree
      - vim
      - ntpdate
      - curl
      - wget
      - lshw
      - tcpdump
      - hddtemp
      - uuid-runtime
      - imagemagick
      - ffmpeg
      - aspell
      - aspell-en
      - net-tools
      - libtool
      - ethtool
      - dnsutils
      - dnsmasq
      - git
      - gnupg
      - build-essential
      - autoconf-archive
      - pkg-config

- name: Remove useless packages from the cache
  become: true
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Enable service ssh
  become: true
  systemd:
    name: ssh
    enabled: yes
    masked: no

- name: Enable service timesyncd
  become: true
  systemd:
    name: systemd-timesyncd
    enabled: yes
    masked: no

- name: Set timezone to UTC.
  become: true
  timezone:
    name: UTC

- name: Make sure cron is enable.
  become: true
  systemd:
    name: cron.target
    enabled: yes

- name: Change root's password.
  become: true
  shell: echo "root:$(pwgen 32 1)" | chpasswd

- name: Change users's password.
  become: true
  shell: echo "{{ansible_user}}:$(pwgen 32 1)" | chpasswd

- name: Change default editor to vim
  become: true
  shell: update-alternatives --set editor /usr/bin/vim.basic

- name: Install python packages
  pip:
    executable: pip3
    name:
      - wheel
